"""

Revision ID: ac41e5fe1929
Revises: 7d00562b9251
Create Date: 2026-07-31 16:15:20.573099

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac41e5fe1929'
down_revision: str | Sequence[str] | None = '7d00562b9251'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('int1', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('int2', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('limit', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('str1', sa.String(length=50), nullable=False))
    op.add_column('statistics', sa.Column('str2', sa.String(length=50), nullable=False))
    op.add_column('statistics', sa.Column('hits', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('statistics', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uniq_statistics_request', 'statistics', ['int1', 'int2', 'limit', 'str1', 'str2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_statistics_request', 'statistics', type_='unique')
    op.drop_column('statistics', 'updated_at')
    op.drop_column('statistics', 'created_at')
    op.drop_column('statistics', 'hits')
    op.drop_column('statistics', 'str2')
    op.drop_column('statistics', 'str1')
    op.drop_column('statistics', 'limit')
    op.drop_column('statistics', 'int2')
    op.drop_column('statistics', 'int1')
    # ### end Alembic commands ###
